// Code generated by Kitex v0.14.1. DO NOT EDIT.
package basicmanagementservice

import (
	manageservice "github.com/AI-MyPresenceing/coach-idl/kitex_gen/coach/basic/manageservice"
	server "github.com/cloudwego/kitex/server"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler manageservice.BasicManagementService, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)
	options = append(options, server.WithCompatibleMiddlewareForUnary())

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}

func RegisterService(svr server.Server, handler manageservice.BasicManagementService, opts ...server.RegisterOption) error {
	return svr.RegisterService(serviceInfo(), handler, opts...)
}
